version: '3.7'
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes