version: '3.7'
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app

  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'
